#[derive(
    Debug,
    strum_macros::EnumIter,
    strum_macros::EnumString,
    strum_macros::Display,
    strum_macros::IntoStaticStr,
    Clone,
    Copy
)]
pub enum BoardCoordinate {
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,

    B1,
    B2,
    B3,
    B4,
    B5,
    B6,
    B7,
    B8,

    C1,
    C2,
    C3,
    C4,
    C5,
    C6,
    C7,
    C8,

    D1,
    D2,
    D3,
    D4,
    D5,
    D6,
    D7,
    D8,

    E1,
    E2,
    E3,
    E4,
    E5,
    E6,
    E7,
    E8,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,

    G1,
    G2,
    G3,
    G4,
    G5,
    G6,
    G7,
    G8,

    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    H7,
    H8,
}

impl BoardCoordinate {
    pub fn as_coords(&self) -> (usize, usize) {
        match self {
            BoardCoordinate::A1 => (0, 0),
            BoardCoordinate::A2 => (0, 1),
            BoardCoordinate::A3 => (0, 2),
            BoardCoordinate::A4 => (0, 3),
            BoardCoordinate::A5 => (0, 4),
            BoardCoordinate::A6 => (0, 5),
            BoardCoordinate::A7 => (0, 6),
            BoardCoordinate::A8 => (0, 7),
            BoardCoordinate::B1 => (1, 0),
            BoardCoordinate::B2 => (1, 1),
            BoardCoordinate::B3 => (1, 2),
            BoardCoordinate::B4 => (1, 3),
            BoardCoordinate::B5 => (1, 4),
            BoardCoordinate::B6 => (1, 5),
            BoardCoordinate::B7 => (1, 6),
            BoardCoordinate::B8 => (1, 7),
            BoardCoordinate::C1 => (2, 0),
            BoardCoordinate::C2 => (2, 1),
            BoardCoordinate::C3 => (2, 2),
            BoardCoordinate::C4 => (2, 3),
            BoardCoordinate::C5 => (2, 4),
            BoardCoordinate::C6 => (2, 5),
            BoardCoordinate::C7 => (2, 6),
            BoardCoordinate::C8 => (2, 7),
            BoardCoordinate::D1 => (3, 0),
            BoardCoordinate::D2 => (3, 1),
            BoardCoordinate::D3 => (3, 2),
            BoardCoordinate::D4 => (3, 3),
            BoardCoordinate::D5 => (3, 4),
            BoardCoordinate::D6 => (3, 5),
            BoardCoordinate::D7 => (3, 6),
            BoardCoordinate::D8 => (3, 7),
            BoardCoordinate::E1 => (4, 0),
            BoardCoordinate::E2 => (4, 1),
            BoardCoordinate::E3 => (4, 2),
            BoardCoordinate::E4 => (4, 3),
            BoardCoordinate::E5 => (4, 4),
            BoardCoordinate::E6 => (4, 5),
            BoardCoordinate::E7 => (4, 6),
            BoardCoordinate::E8 => (4, 7),
            BoardCoordinate::F1 => (5, 0),
            BoardCoordinate::F2 => (5, 1),
            BoardCoordinate::F3 => (5, 2),
            BoardCoordinate::F4 => (5, 3),
            BoardCoordinate::F5 => (5, 4),
            BoardCoordinate::F6 => (5, 5),
            BoardCoordinate::F7 => (5, 6),
            BoardCoordinate::F8 => (5, 7),
            BoardCoordinate::G1 => (6, 0),
            BoardCoordinate::G2 => (6, 1),
            BoardCoordinate::G3 => (6, 2),
            BoardCoordinate::G4 => (6, 3),
            BoardCoordinate::G5 => (6, 4),
            BoardCoordinate::G6 => (6, 5),
            BoardCoordinate::G7 => (6, 6),
            BoardCoordinate::G8 => (6, 7),
            BoardCoordinate::H1 => (7, 0),
            BoardCoordinate::H2 => (7, 1),
            BoardCoordinate::H3 => (7, 2),
            BoardCoordinate::H4 => (7, 3),
            BoardCoordinate::H5 => (7, 4),
            BoardCoordinate::H6 => (7, 5),
            BoardCoordinate::H7 => (7, 6),
            BoardCoordinate::H8 => (7, 7),
        }
    }
}
