
#[derive(strum_macros::EnumIter, strum_macros::EnumString)]
pub enum BoardCoordinates {
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,

    B1,
    B2,
    B3,
    B4,
    B5,
    B6,
    B7,
    B8,

    C1,
    C2,
    C3,
    C4,
    C5,
    C6,
    C7,
    C8,

    D1,
    D2,
    D3,
    D4,
    D5,
    D6,
    D7,
    D8,

    E1,
    E2,
    E3,
    E4,
    E5,
    E6,
    E7,
    E8,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,

    G1,
    G2,
    G3,
    G4,
    G5,
    G6,
    G7,
    G8,

    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    H7,
    H8,
}

impl BoardCoordinates {
    pub fn as_coords(self) -> (usize, usize) {
        match self {
            BoardCoordinates::A1 => (0, 0),
            BoardCoordinates::A2 => (0, 1),
            BoardCoordinates::A3 => (0, 2),
            BoardCoordinates::A4 => (0, 3),
            BoardCoordinates::A5 => (0, 4),
            BoardCoordinates::A6 => (0, 5),
            BoardCoordinates::A7 => (0, 6),
            BoardCoordinates::A8 => (0, 7),
            BoardCoordinates::B1 => (1, 0),
            BoardCoordinates::B2 => (1, 1),
            BoardCoordinates::B3 => (1, 2),
            BoardCoordinates::B4 => (1, 3),
            BoardCoordinates::B5 => (1, 4),
            BoardCoordinates::B6 => (1, 5),
            BoardCoordinates::B7 => (1, 6),
            BoardCoordinates::B8 => (1, 7),
            BoardCoordinates::C1 => (2, 0),
            BoardCoordinates::C2 => (2, 1),
            BoardCoordinates::C3 => (2, 2),
            BoardCoordinates::C4 => (2, 3),
            BoardCoordinates::C5 => (2, 4),
            BoardCoordinates::C6 => (2, 5),
            BoardCoordinates::C7 => (2, 6),
            BoardCoordinates::C8 => (2, 7),
            BoardCoordinates::D1 => (3, 0),
            BoardCoordinates::D2 => (3, 1),
            BoardCoordinates::D3 => (3, 2),
            BoardCoordinates::D4 => (3, 3),
            BoardCoordinates::D5 => (3, 4),
            BoardCoordinates::D6 => (3, 5),
            BoardCoordinates::D7 => (3, 6),
            BoardCoordinates::D8 => (3, 7),
            BoardCoordinates::E1 => (4, 0),
            BoardCoordinates::E2 => (4, 1),
            BoardCoordinates::E3 => (4, 2),
            BoardCoordinates::E4 => (4, 3),
            BoardCoordinates::E5 => (4, 4),
            BoardCoordinates::E6 => (4, 5),
            BoardCoordinates::E7 => (4, 6),
            BoardCoordinates::E8 => (4, 7),
            BoardCoordinates::F1 => (5, 0),
            BoardCoordinates::F2 => (5, 1),
            BoardCoordinates::F3 => (5, 2),
            BoardCoordinates::F4 => (5, 3),
            BoardCoordinates::F5 => (5, 4),
            BoardCoordinates::F6 => (5, 5),
            BoardCoordinates::F7 => (5, 6),
            BoardCoordinates::F8 => (5, 7),
            BoardCoordinates::G1 => (6, 0),
            BoardCoordinates::G2 => (6, 1),
            BoardCoordinates::G3 => (6, 2),
            BoardCoordinates::G4 => (6, 3),
            BoardCoordinates::G5 => (6, 4),
            BoardCoordinates::G6 => (6, 5),
            BoardCoordinates::G7 => (6, 6),
            BoardCoordinates::G8 => (6, 7),
            BoardCoordinates::H1 => (7, 0),
            BoardCoordinates::H2 => (7, 1),
            BoardCoordinates::H3 => (7, 2),
            BoardCoordinates::H4 => (7, 3),
            BoardCoordinates::H5 => (7, 4),
            BoardCoordinates::H6 => (7, 5),
            BoardCoordinates::H7 => (7, 6),
            BoardCoordinates::H8 => (7, 7),
        }
    }
}
